version: "3.8"

networks:
  default:
    name: dcwiz-app

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 2s
      retries: 15
    networks:
      default:
        aliases:
          - postgres

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      default:
        aliases:
          - redis

  pause:
    image: ubuntu
    command: sleep 10
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  prepare-database:
    image: postgres:15
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    depends_on:
      pause:
        condition: service_completed_successfully
    volumes:
      - ./scripts:/opt/scripts
    command: /opt/scripts/create_postgres_database.sh ${POSTGRES_DB} ${POSTGRES_USER} ${POSTGRES_PASSWORD}
