name: Deploy
on:
  push:
    branches:
      - main
      - develop
      - experimental
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'docs/**'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set vars
        id: vars
        env:
          REF: {{ '${{ github.ref }}' }}
        run: |
          if [ $REF == 'refs/heads/main' ]
          then
              echo "::set-output name=branch::main"
          elif [ $REF == 'refs/heads/develop' ]
          then
              echo "::set-output name=branch::develop"
          else
              echo "::set-output name=branch::experimental
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: {{ '${{ github.actor }}' }}
          password: {{ '${{ secrets.GITHUB_TOKEN }}' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/cap-dcwiz/{{ cookiecutter.image_name }}:{{ '${{ steps.vars.outputs.branch }}' }}

      - name: Deploy
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/up.yaml
          key: {{ '${{secrets.SSH_PRIVATE_KEY}}' }}
          options:
            -i ansible/hosts.yaml 
            -e host_group={{ '${{ steps.vars.outputs.branch }}' }}