{{ cookiecutter.__container_name }}:
  install_relations:
    - scope:{{ cookiecutter.__container_name }}=child@scope:system
    - scope:system=parent@scope:{{ cookiecutter.__container_name }}
  conditions:
    /:
      GET:
        - "{user}=user@scope:{{ cookiecutter.__container_name }}"
    /(\w):
      GET:
        - "{user}=user@scope:{{ cookiecutter.__container_name }}"