[auth]
#url = "https://auth.experimental.rda.ai/auth/"

[sqlalchemy]
#url = "postgresql+asyncpg://postgres:postgres@postgres:5432/{{ cookiecutter.app_path.replace('-', '_') }}"

[redis]
#host = "localhost"
#port = 6379
#db = 0
#password = "redis"

[platform]
#username = "user"
#password = "password"
#base_url = "https://dcwiz-platform.dev.rda.ai"
#cache_ttl = 120
#cache_ttl_var = 60
#timeout = 60
#verify = false
