- name: Run using a project directory
  hosts: {{ "'{{ host_group }}'" }}
  vars:
    app_name: {{ cookiecutter.__project_folder }}
    local_authz_pos: export/authz.yaml
    env_pos: {{ "'{{ ansible_env.HOME }}/dcwiz-deploy-prepare/envs/{{ app_name }}'" }}
    authz_pos: {{ "'{{ ansible_env.HOME }}/dcwiz-auth-stack/config/def.d/{{ app_name }}.yaml'" }}
    pos: {{ "'{{ ansible_env.HOME }}/{{ app_name }}/'" }}
  tasks:
    - name: set var env_file to '.env' if not already set
      ansible.builtin.set_fact:
          env_file: '.env'
      when: env_file is not defined
    - name: populate {{ "{{ env_file }}" }} to host
      ansible.builtin.copy:
        src: {{ "'../{{ env_file }}'" }}
        dest: {{ "'{{ env_pos }}'" }}
      when: env_file is file
    - name: populate authz definition to host if exists
      ansible.builtin.copy:
        src: {{ "'../{{ local_authz_pos }}'" }}
        dest: {{ "'{{ authz_pos }}'" }}
      when: local_authz_pos is file
    - name: request auth-service to reload authz definition
      uri:
        url: 'https://localhost/auth/authz/reload'
        method: GET
        status_code: 200
        validate_certs: false
