- name: Run using a project directory
  hosts: {{ "'{{ host_group }}'" }}
  vars:
    env_pos: {{ "'{{ ansible_env.HOME }}/dcwiz-deploy-prepare/envs/" }}{{ cookiecutter.__project_folder }}'
    pos: {{ "'{{ ansible_env.HOME }}/" }}{{ cookiecutter.__project_folder }}/'
  tasks: 
    - name: send config to host
      ansible.builtin.copy:
        src: ../config
        dest: {{ "'{{ pos }}'" }}
    - name: send resources to host
      ansible.builtin.copy:
        src: ../resources
        dest: {{ "'{{ pos }}'" }}
    - name: send scripts to host
      ansible.builtin.copy:
        src: ../scripts
        dest: {{ "'{{ pos }}'" }}
        mode: 0757
    - name: send docker-compose.yml to host
      ansible.builtin.copy:
        src: ../docker-compose.yaml
        dest: {{ "'{{ pos }}'" }}
    - name: read env_pos file info
      ansible.builtin.stat:
        path: {{ "'{{ env_pos }}'" }}
      register: env_pos_stat
    - name: copy .env to host if exists
      ansible.builtin.copy:
        src: {{ "'{{ env_pos }}'" }}
        dest: {{ "'{{ pos }}/.env'" }}
        remote_src: true
      when: env_pos_stat.stat.exists
    - name: start docker-compose
      community.docker.docker_compose:
        project_src: {{ "'{{ pos }}'" }}
        state: present
        pull: true
        build: true
