- name: Run using a project directory
  hosts: {{ "'{{ host_group }}'" }}
  vars:
    app_name: {{ cookiecutter.__project_folder }}
    env_pos: {{ "'{{ ansible_env.HOME }}/dcwiz-deploy-prepare/envs/{{ app_name }}'" }}
    pos: {{ "'{{ ansible_env.HOME }}/{{ app_name }}'" }}
  tasks: 
    - name: send config to host
      ansible.builtin.copy:
        src: ../config
        dest: {{ "'{{ pos }}'" }}
      when: "'config' is exists"
    - name: send resources to host
      ansible.builtin.copy:
        src: ../resources
        dest: {{ "'{{ pos }}'" }}
      when: "'resources' is exists"
    - name: send scripts to host
      ansible.builtin.copy:
        src: ../scripts
        dest: {{ "'{{ pos }}'" }}
        mode: 0757
      when: "'scripts' is exists"
    - name: send docker-compose.yml to host
      ansible.builtin.copy:
        src: ../docker-compose.prod.yaml
        dest: {{ "'{{ pos }}/docker-compose.yaml'" }}
    - name: read env_pos file info
      ansible.builtin.stat:
        path: {{ "'{{ env_pos }}'" }}
      register: env_pos_stat
    - name: copy .env to host if exists
      ansible.builtin.copy:
        src: {{ "'{{ env_pos }}'" }}
        dest: {{ "'{{ pos }}/.env'" }}
        remote_src: true
      when: env_pos_stat.stat.exists
    - name: start docker-compose
      environment:
        IMAGE_TAG: {{ "'{{ host_group }}'" }}
      community.docker.docker_compose:
        project_src: {{ "'{{ pos }}'" }}
        state: present
        pull: true
        build: true
        profiles: "app"
