name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - '.gitignore'
      - 'docs/**'

jobs:
  Build-Docker-Images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract long version from pyproject.toml
        run: echo "IMAGE_VERSION_LONG=$(grep '^version' pyproject.toml | awk -F' = |\"' '{print $3}')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: {{ '${{ github.actor }}' }}
          password: {{ '${{ secrets.GITHUB_TOKEN }}' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/cap-dcwiz/{{ cookiecutter.__image_name }}:{{ '${{ env.IMAGE_VERSION_LONG }}' }}